[project]
name = "tictactoegame"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "nuitka>=2.8.10",
    "pygame>=2.6.1",
    "zstandard>=0.25.0",
]
